apiVersion: kctrl.carvel.dev/v1alpha1
kind: PackageBuild
metadata:
  creationTimestamp: null
  name: external-secrets.external-secrets.io
spec:
  release:
  - resource: {}
  template:
    spec:
      app:
        spec:
          deploy:
          - kapp: {}
          template:
          - helmTemplate:
              path: upstream
          - ytt:
              paths:
              - '-'
          - kbld: {}
      export:
      - imgpkgBundle:
          image: ghcr.io/warroyo/tpk8s-custom-capabilities/eso-package
          useKbldImagesLock: true
        includePaths:
        - upstream
