apiVersion: vendir.k14s.io/v1alpha1
directories:
- contents:
  - helmChart:
      name: external-secrets
      repository:
        url: https://charts.external-secrets.io
      version: 0.10.0
    path: .
  path: upstream
kind: Config
minimumRequiredVersion: ""
